# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_documentai_api_client
from cloudmersive_documentai_api_client.models.split_document_response import SplitDocumentResponse  # noqa: E501
from cloudmersive_documentai_api_client.rest import ApiException


class TestSplitDocumentResponse(unittest.TestCase):
    """SplitDocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSplitDocumentResponse(self):
        """Test SplitDocumentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_documentai_api_client.models.split_document_response.SplitDocumentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
