# coding: utf-8

"""
    Document AI API

    Use next-generation AI to extract data, fields, insights and text from documents. Instantly.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_documentai_api_client
from cloudmersive_documentai_api_client.models.document_question_boolean import DocumentQuestionBoolean  # noqa: E501
from cloudmersive_documentai_api_client.rest import ApiException


class TestDocumentQuestionBoolean(unittest.TestCase):
    """DocumentQuestionBoolean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentQuestionBoolean(self):
        """Test DocumentQuestionBoolean"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_documentai_api_client.models.document_question_boolean.DocumentQuestionBoolean()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
