# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentQuestionAnswerItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'question_id': 'str',
        'answer_value': 'str',
        'answer_rationale': 'str',
        'confidence_score': 'float'
    }

    attribute_map = {
        'question_id': 'QuestionId',
        'answer_value': 'AnswerValue',
        'answer_rationale': 'AnswerRationale',
        'confidence_score': 'ConfidenceScore'
    }

    def __init__(self, question_id=None, answer_value=None, answer_rationale=None, confidence_score=None):  # noqa: E501
        """DocumentQuestionAnswerItem - a model defined in Swagger"""  # noqa: E501

        self._question_id = None
        self._answer_value = None
        self._answer_rationale = None
        self._confidence_score = None
        self.discriminator = None

        if question_id is not None:
            self.question_id = question_id
        if answer_value is not None:
            self.answer_value = answer_value
        if answer_rationale is not None:
            self.answer_rationale = answer_rationale
        if confidence_score is not None:
            self.confidence_score = confidence_score

    @property
    def question_id(self):
        """Gets the question_id of this DocumentQuestionAnswerItem.  # noqa: E501

        ID of the input question  # noqa: E501

        :return: The question_id of this DocumentQuestionAnswerItem.  # noqa: E501
        :rtype: str
        """
        return self._question_id

    @question_id.setter
    def question_id(self, question_id):
        """Sets the question_id of this DocumentQuestionAnswerItem.

        ID of the input question  # noqa: E501

        :param question_id: The question_id of this DocumentQuestionAnswerItem.  # noqa: E501
        :type: str
        """

        self._question_id = question_id

    @property
    def answer_value(self):
        """Gets the answer_value of this DocumentQuestionAnswerItem.  # noqa: E501

        Answer response value, formatted as a string, for this question.  Boolean questions will return YES or NO.  # noqa: E501

        :return: The answer_value of this DocumentQuestionAnswerItem.  # noqa: E501
        :rtype: str
        """
        return self._answer_value

    @answer_value.setter
    def answer_value(self, answer_value):
        """Sets the answer_value of this DocumentQuestionAnswerItem.

        Answer response value, formatted as a string, for this question.  Boolean questions will return YES or NO.  # noqa: E501

        :param answer_value: The answer_value of this DocumentQuestionAnswerItem.  # noqa: E501
        :type: str
        """

        self._answer_value = answer_value

    @property
    def answer_rationale(self):
        """Gets the answer_rationale of this DocumentQuestionAnswerItem.  # noqa: E501

        Rationale explaining why this answer was given  # noqa: E501

        :return: The answer_rationale of this DocumentQuestionAnswerItem.  # noqa: E501
        :rtype: str
        """
        return self._answer_rationale

    @answer_rationale.setter
    def answer_rationale(self, answer_rationale):
        """Sets the answer_rationale of this DocumentQuestionAnswerItem.

        Rationale explaining why this answer was given  # noqa: E501

        :param answer_rationale: The answer_rationale of this DocumentQuestionAnswerItem.  # noqa: E501
        :type: str
        """

        self._answer_rationale = answer_rationale

    @property
    def confidence_score(self):
        """Gets the confidence_score of this DocumentQuestionAnswerItem.  # noqa: E501

        Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence  # noqa: E501

        :return: The confidence_score of this DocumentQuestionAnswerItem.  # noqa: E501
        :rtype: float
        """
        return self._confidence_score

    @confidence_score.setter
    def confidence_score(self, confidence_score):
        """Sets the confidence_score of this DocumentQuestionAnswerItem.

        Confidence score between 0.0 and 1.0 where values above 0.8 indicate high confidence  # noqa: E501

        :param confidence_score: The confidence_score of this DocumentQuestionAnswerItem.  # noqa: E501
        :type: float
        """

        self._confidence_score = confidence_score

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentQuestionAnswerItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentQuestionAnswerItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
