# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentQuestionsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_file': 'str',
        'questions_yes_no': 'list[DocumentQuestionBoolean]',
        'questions_multiple_choice': 'list[DocumentQuestionMultipleChoice]',
        'questions_free_response': 'list[DocumentQuestionFreeResponse]',
        'recognition_mode': 'str'
    }

    attribute_map = {
        'input_file': 'InputFile',
        'questions_yes_no': 'QuestionsYesNo',
        'questions_multiple_choice': 'QuestionsMultipleChoice',
        'questions_free_response': 'QuestionsFreeResponse',
        'recognition_mode': 'RecognitionMode'
    }

    def __init__(self, input_file=None, questions_yes_no=None, questions_multiple_choice=None, questions_free_response=None, recognition_mode=None):  # noqa: E501
        """DocumentQuestionsRequest - a model defined in Swagger"""  # noqa: E501

        self._input_file = None
        self._questions_yes_no = None
        self._questions_multiple_choice = None
        self._questions_free_response = None
        self._recognition_mode = None
        self.discriminator = None

        if input_file is not None:
            self.input_file = input_file
        if questions_yes_no is not None:
            self.questions_yes_no = questions_yes_no
        if questions_multiple_choice is not None:
            self.questions_multiple_choice = questions_multiple_choice
        if questions_free_response is not None:
            self.questions_free_response = questions_free_response
        if recognition_mode is not None:
            self.recognition_mode = recognition_mode

    @property
    def input_file(self):
        """Gets the input_file of this DocumentQuestionsRequest.  # noqa: E501

        Input file as a byte array  # noqa: E501

        :return: The input_file of this DocumentQuestionsRequest.  # noqa: E501
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file):
        """Sets the input_file of this DocumentQuestionsRequest.

        Input file as a byte array  # noqa: E501

        :param input_file: The input_file of this DocumentQuestionsRequest.  # noqa: E501
        :type: str
        """
        if input_file is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', input_file):  # noqa: E501
            raise ValueError(r"Invalid value for `input_file`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._input_file = input_file

    @property
    def questions_yes_no(self):
        """Gets the questions_yes_no of this DocumentQuestionsRequest.  # noqa: E501

        Optional: Yes or No boolean questions to answer about the document  # noqa: E501

        :return: The questions_yes_no of this DocumentQuestionsRequest.  # noqa: E501
        :rtype: list[DocumentQuestionBoolean]
        """
        return self._questions_yes_no

    @questions_yes_no.setter
    def questions_yes_no(self, questions_yes_no):
        """Sets the questions_yes_no of this DocumentQuestionsRequest.

        Optional: Yes or No boolean questions to answer about the document  # noqa: E501

        :param questions_yes_no: The questions_yes_no of this DocumentQuestionsRequest.  # noqa: E501
        :type: list[DocumentQuestionBoolean]
        """

        self._questions_yes_no = questions_yes_no

    @property
    def questions_multiple_choice(self):
        """Gets the questions_multiple_choice of this DocumentQuestionsRequest.  # noqa: E501

        Optional: Multiple choice questions to answer about the document  # noqa: E501

        :return: The questions_multiple_choice of this DocumentQuestionsRequest.  # noqa: E501
        :rtype: list[DocumentQuestionMultipleChoice]
        """
        return self._questions_multiple_choice

    @questions_multiple_choice.setter
    def questions_multiple_choice(self, questions_multiple_choice):
        """Sets the questions_multiple_choice of this DocumentQuestionsRequest.

        Optional: Multiple choice questions to answer about the document  # noqa: E501

        :param questions_multiple_choice: The questions_multiple_choice of this DocumentQuestionsRequest.  # noqa: E501
        :type: list[DocumentQuestionMultipleChoice]
        """

        self._questions_multiple_choice = questions_multiple_choice

    @property
    def questions_free_response(self):
        """Gets the questions_free_response of this DocumentQuestionsRequest.  # noqa: E501

        Optional: Free response questions to answer about the document  # noqa: E501

        :return: The questions_free_response of this DocumentQuestionsRequest.  # noqa: E501
        :rtype: list[DocumentQuestionFreeResponse]
        """
        return self._questions_free_response

    @questions_free_response.setter
    def questions_free_response(self, questions_free_response):
        """Sets the questions_free_response of this DocumentQuestionsRequest.

        Optional: Free response questions to answer about the document  # noqa: E501

        :param questions_free_response: The questions_free_response of this DocumentQuestionsRequest.  # noqa: E501
        :type: list[DocumentQuestionFreeResponse]
        """

        self._questions_free_response = questions_free_response

    @property
    def recognition_mode(self):
        """Gets the recognition_mode of this DocumentQuestionsRequest.  # noqa: E501

        Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images  # noqa: E501

        :return: The recognition_mode of this DocumentQuestionsRequest.  # noqa: E501
        :rtype: str
        """
        return self._recognition_mode

    @recognition_mode.setter
    def recognition_mode(self, recognition_mode):
        """Sets the recognition_mode of this DocumentQuestionsRequest.

        Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images  # noqa: E501

        :param recognition_mode: The recognition_mode of this DocumentQuestionsRequest.  # noqa: E501
        :type: str
        """

        self._recognition_mode = recognition_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentQuestionsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentQuestionsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
