# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentQuestionBoolean(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'question_id': 'str',
        'question_text': 'str'
    }

    attribute_map = {
        'question_id': 'QuestionId',
        'question_text': 'QuestionText'
    }

    def __init__(self, question_id=None, question_text=None):  # noqa: E501
        """DocumentQuestionBoolean - a model defined in Swagger"""  # noqa: E501

        self._question_id = None
        self._question_text = None
        self.discriminator = None

        if question_id is not None:
            self.question_id = question_id
        if question_text is not None:
            self.question_text = question_text

    @property
    def question_id(self):
        """Gets the question_id of this DocumentQuestionBoolean.  # noqa: E501

        Unique ID of the question, e.g. 1 or 2A  # noqa: E501

        :return: The question_id of this DocumentQuestionBoolean.  # noqa: E501
        :rtype: str
        """
        return self._question_id

    @question_id.setter
    def question_id(self, question_id):
        """Sets the question_id of this DocumentQuestionBoolean.

        Unique ID of the question, e.g. 1 or 2A  # noqa: E501

        :param question_id: The question_id of this DocumentQuestionBoolean.  # noqa: E501
        :type: str
        """

        self._question_id = question_id

    @property
    def question_text(self):
        """Gets the question_text of this DocumentQuestionBoolean.  # noqa: E501

        Question in natural language to ask of the document where the answer resolves to YES or NO, e.g. 'Is this document signed and countersigned by both parties?'  # noqa: E501

        :return: The question_text of this DocumentQuestionBoolean.  # noqa: E501
        :rtype: str
        """
        return self._question_text

    @question_text.setter
    def question_text(self, question_text):
        """Sets the question_text of this DocumentQuestionBoolean.

        Question in natural language to ask of the document where the answer resolves to YES or NO, e.g. 'Is this document signed and countersigned by both parties?'  # noqa: E501

        :param question_text: The question_text of this DocumentQuestionBoolean.  # noqa: E501
        :type: str
        """

        self._question_text = question_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentQuestionBoolean, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentQuestionBoolean):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
