# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentPolicyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'input_file': 'str',
        'rules': 'list[PolicyRule]',
        'recognition_mode': 'str'
    }

    attribute_map = {
        'input_file': 'InputFile',
        'rules': 'Rules',
        'recognition_mode': 'RecognitionMode'
    }

    def __init__(self, input_file=None, rules=None, recognition_mode=None):  # noqa: E501
        """DocumentPolicyRequest - a model defined in Swagger"""  # noqa: E501

        self._input_file = None
        self._rules = None
        self._recognition_mode = None
        self.discriminator = None

        if input_file is not None:
            self.input_file = input_file
        if rules is not None:
            self.rules = rules
        if recognition_mode is not None:
            self.recognition_mode = recognition_mode

    @property
    def input_file(self):
        """Gets the input_file of this DocumentPolicyRequest.  # noqa: E501

        Input file as a byte array  # noqa: E501

        :return: The input_file of this DocumentPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._input_file

    @input_file.setter
    def input_file(self, input_file):
        """Sets the input_file of this DocumentPolicyRequest.

        Input file as a byte array  # noqa: E501

        :param input_file: The input_file of this DocumentPolicyRequest.  # noqa: E501
        :type: str
        """
        if input_file is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', input_file):  # noqa: E501
            raise ValueError(r"Invalid value for `input_file`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._input_file = input_file

    @property
    def rules(self):
        """Gets the rules of this DocumentPolicyRequest.  # noqa: E501

        Rules to apply to the document  # noqa: E501

        :return: The rules of this DocumentPolicyRequest.  # noqa: E501
        :rtype: list[PolicyRule]
        """
        return self._rules

    @rules.setter
    def rules(self, rules):
        """Sets the rules of this DocumentPolicyRequest.

        Rules to apply to the document  # noqa: E501

        :param rules: The rules of this DocumentPolicyRequest.  # noqa: E501
        :type: list[PolicyRule]
        """

        self._rules = rules

    @property
    def recognition_mode(self):
        """Gets the recognition_mode of this DocumentPolicyRequest.  # noqa: E501

        Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images  # noqa: E501

        :return: The recognition_mode of this DocumentPolicyRequest.  # noqa: E501
        :rtype: str
        """
        return self._recognition_mode

    @recognition_mode.setter
    def recognition_mode(self, recognition_mode):
        """Sets the recognition_mode of this DocumentPolicyRequest.

        Optional; Recognition mode - Normal (default) provides the highest accuracy but slower speed, while Normal provides faster response but lower accuracy for low quality images  # noqa: E501

        :param recognition_mode: The recognition_mode of this DocumentPolicyRequest.  # noqa: E501
        :type: str
        """

        self._recognition_mode = recognition_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentPolicyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentPolicyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
