# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentQuestionChoiceItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'choice_id': 'str',
        'choice_text': 'str'
    }

    attribute_map = {
        'choice_id': 'ChoiceId',
        'choice_text': 'ChoiceText'
    }

    def __init__(self, choice_id=None, choice_text=None):  # noqa: E501
        """DocumentQuestionChoiceItem - a model defined in Swagger"""  # noqa: E501

        self._choice_id = None
        self._choice_text = None
        self.discriminator = None

        if choice_id is not None:
            self.choice_id = choice_id
        if choice_text is not None:
            self.choice_text = choice_text

    @property
    def choice_id(self):
        """Gets the choice_id of this DocumentQuestionChoiceItem.  # noqa: E501

        Unique ID of the response choice, e.g. 3C  # noqa: E501

        :return: The choice_id of this DocumentQuestionChoiceItem.  # noqa: E501
        :rtype: str
        """
        return self._choice_id

    @choice_id.setter
    def choice_id(self, choice_id):
        """Sets the choice_id of this DocumentQuestionChoiceItem.

        Unique ID of the response choice, e.g. 3C  # noqa: E501

        :param choice_id: The choice_id of this DocumentQuestionChoiceItem.  # noqa: E501
        :type: str
        """

        self._choice_id = choice_id

    @property
    def choice_text(self):
        """Gets the choice_text of this DocumentQuestionChoiceItem.  # noqa: E501

        Description text of this choice, e.g. 'Delaware'  # noqa: E501

        :return: The choice_text of this DocumentQuestionChoiceItem.  # noqa: E501
        :rtype: str
        """
        return self._choice_text

    @choice_text.setter
    def choice_text(self, choice_text):
        """Sets the choice_text of this DocumentQuestionChoiceItem.

        Description text of this choice, e.g. 'Delaware'  # noqa: E501

        :param choice_text: The choice_text of this DocumentQuestionChoiceItem.  # noqa: E501
        :type: str
        """

        self._choice_text = choice_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DocumentQuestionChoiceItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentQuestionChoiceItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
