# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SplitDocumentResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'successful': 'bool',
        'sub_documents': 'list[SubDocument]'
    }

    attribute_map = {
        'successful': 'Successful',
        'sub_documents': 'SubDocuments'
    }

    def __init__(self, successful=None, sub_documents=None):  # noqa: E501
        """SplitDocumentResponse - a model defined in Swagger"""  # noqa: E501

        self._successful = None
        self._sub_documents = None
        self.discriminator = None

        if successful is not None:
            self.successful = successful
        if sub_documents is not None:
            self.sub_documents = sub_documents

    @property
    def successful(self):
        """Gets the successful of this SplitDocumentResponse.  # noqa: E501

        True if successful, false otherwise  # noqa: E501

        :return: The successful of this SplitDocumentResponse.  # noqa: E501
        :rtype: bool
        """
        return self._successful

    @successful.setter
    def successful(self, successful):
        """Sets the successful of this SplitDocumentResponse.

        True if successful, false otherwise  # noqa: E501

        :param successful: The successful of this SplitDocumentResponse.  # noqa: E501
        :type: bool
        """

        self._successful = successful

    @property
    def sub_documents(self):
        """Gets the sub_documents of this SplitDocumentResponse.  # noqa: E501

        The sub-documents that were identified and extracted from the input document  # noqa: E501

        :return: The sub_documents of this SplitDocumentResponse.  # noqa: E501
        :rtype: list[SubDocument]
        """
        return self._sub_documents

    @sub_documents.setter
    def sub_documents(self, sub_documents):
        """Sets the sub_documents of this SplitDocumentResponse.

        The sub-documents that were identified and extracted from the input document  # noqa: E501

        :param sub_documents: The sub_documents of this SplitDocumentResponse.  # noqa: E501
        :type: list[SubDocument]
        """

        self._sub_documents = sub_documents

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SplitDocumentResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SplitDocumentResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
