# coding: utf-8

"""
    Document AI API

    Extract structured data including named fields, tables, barcodes, classifications, and summaries from common document formats, scanned documents, and photos of documents using AI.  Also supports handwriting and low quality photos and scans, as well as digital document input.  Supports a wide range of languages, and is able to analyze and infer semantic structure from the visual layout for documents.  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudmersive.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SubDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_page': 'int',
        'end_page': 'int',
        'document_description': 'str',
        'file_bytes': 'str'
    }

    attribute_map = {
        'start_page': 'StartPage',
        'end_page': 'EndPage',
        'document_description': 'DocumentDescription',
        'file_bytes': 'FileBytes'
    }

    def __init__(self, start_page=None, end_page=None, document_description=None, file_bytes=None):  # noqa: E501
        """SubDocument - a model defined in Swagger"""  # noqa: E501

        self._start_page = None
        self._end_page = None
        self._document_description = None
        self._file_bytes = None
        self.discriminator = None

        if start_page is not None:
            self.start_page = start_page
        if end_page is not None:
            self.end_page = end_page
        if document_description is not None:
            self.document_description = document_description
        if file_bytes is not None:
            self.file_bytes = file_bytes

    @property
    def start_page(self):
        """Gets the start_page of this SubDocument.  # noqa: E501

        Starting page number (1-indexed) of this sub-document in the original document  # noqa: E501

        :return: The start_page of this SubDocument.  # noqa: E501
        :rtype: int
        """
        return self._start_page

    @start_page.setter
    def start_page(self, start_page):
        """Sets the start_page of this SubDocument.

        Starting page number (1-indexed) of this sub-document in the original document  # noqa: E501

        :param start_page: The start_page of this SubDocument.  # noqa: E501
        :type: int
        """

        self._start_page = start_page

    @property
    def end_page(self):
        """Gets the end_page of this SubDocument.  # noqa: E501

        Ending page number (1-indexed) of this sub-document in the original document  # noqa: E501

        :return: The end_page of this SubDocument.  # noqa: E501
        :rtype: int
        """
        return self._end_page

    @end_page.setter
    def end_page(self, end_page):
        """Sets the end_page of this SubDocument.

        Ending page number (1-indexed) of this sub-document in the original document  # noqa: E501

        :param end_page: The end_page of this SubDocument.  # noqa: E501
        :type: int
        """

        self._end_page = end_page

    @property
    def document_description(self):
        """Gets the document_description of this SubDocument.  # noqa: E501

        Description of the sub-document including document type and any identifying information such as person name  # noqa: E501

        :return: The document_description of this SubDocument.  # noqa: E501
        :rtype: str
        """
        return self._document_description

    @document_description.setter
    def document_description(self, document_description):
        """Sets the document_description of this SubDocument.

        Description of the sub-document including document type and any identifying information such as person name  # noqa: E501

        :param document_description: The document_description of this SubDocument.  # noqa: E501
        :type: str
        """

        self._document_description = document_description

    @property
    def file_bytes(self):
        """Gets the file_bytes of this SubDocument.  # noqa: E501

        The extracted sub-document as PDF file bytes  # noqa: E501

        :return: The file_bytes of this SubDocument.  # noqa: E501
        :rtype: str
        """
        return self._file_bytes

    @file_bytes.setter
    def file_bytes(self, file_bytes):
        """Sets the file_bytes of this SubDocument.

        The extracted sub-document as PDF file bytes  # noqa: E501

        :param file_bytes: The file_bytes of this SubDocument.  # noqa: E501
        :type: str
        """
        if file_bytes is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', file_bytes):  # noqa: E501
            raise ValueError(r"Invalid value for `file_bytes`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._file_bytes = file_bytes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SubDocument, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubDocument):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
